<?php

namespace vaniacarta74\aRESTy\Tests\unit;

use PHPUnit\Framework\TestCase;
use vaniacarta74\aRESTy\Calculator;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-02-03 at 11:20:53.
 */
class CalculatorTest extends TestCase {

    /**
     * @var Calculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() : void {
        $this->object = new Calculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() : void {
        
    }

    /**
     * Generated from @assert (1, 1) == 2.
     *
     * @covers vaniacarta74\aRESTy\Calculator::add
     */
    public function testAdd() {
        $this->assertEquals(
                2,
                $this->object->add(1, 1)
        );
    }

    /**
     * Generated from @assert (1, 2) == 3.
     *
     * @covers vaniacarta74\aRESTy\Calculator::add
     */
    public function testAdd2() {
        $this->assertEquals(
                3,
                $this->object->add(1, 2)
        );
    }

    /**
     * Generated from @assert (2, 2) == 4.
     *
     * @covers vaniacarta74\aRESTy\Calculator::add
     */
    public function testAdd3() {
        $this->assertEquals(
                4,
                $this->object->add(2, 2)
        );
    }

    /**
     * @covers vaniacarta74\aRESTy\Calculator::sub
     * @todo   Implement testSub().
     */
    public function testSub() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
